FROM oven/bun:1.2.4-alpine AS base

RUN mkdir -p /app/workspace

WORKDIR /app/workspace

FROM base AS dependency_installation

# Copy package files for dependency installation
COPY ./package.json ./package.json
COPY ./bun.lock* ./bun.lock*
COPY ./turbo.json ./turbo.json

# Create directory structure
RUN mkdir -p /app/workspace/core/api /app/workspace/packages

# Install dependencies
COPY ./packages ./packages
COPY ./core/api ./core/api

RUN bun install

FROM dependency_installation AS build_packages

RUN bun run build

RUN bun run check-types

FROM build_packages as api_dev_server

# Expose port
EXPOSE 3000

# Command will be overridden by docker-compose
CMD ["bun", "run", "api-dev"]